# version: '3.9'
# services:
#   upload:
#     build: ./services/upload
#     ports:
#       - "8000:8000"
#     environment:
#       - MINIO_ENDPOINT=minio:9000
#       - MINIO_ACCESS_KEY=minio
#       - MINIO_SECRET_KEY=minio123
#       - MINIO_BUCKET=legal-docs
#       - GROQ_API_KEY=${GROQ_API_KEY}
#       - OPENAI_API_KEY=${OPENAI_API_KEY}
#     depends_on:
#       - minio

#   minio:
#     image: minio/minio
#     command: server /data --console-address ":9001"
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     environment:
#       MINIO_ROOT_USER: minio
#       MINIO_ROOT_PASSWORD: minio123
#     volumes:
#       - minio_data:/data

# volumes:
#   minio_data:




services:
    upload:
      build: ./services/upload
      ports:
        - "8000:8000"
      env_file:
        - .env
      environment:
        - R2_BUCKET_NAME=${R2_BUCKET_NAME}
        - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
        - R2_ACCESS_KEY=${R2_ACCESS_KEY}
        - R2_SECRET_KEY=${R2_SECRET_KEY}
        - R2_ENDPOINT=${R2_ENDPOINT}  
        - R2_PUBLIC_BASE_URL=${R2_PUBLIC_BASE_URL}
      volumes:
        - ./services/upload:/app

    frontend:
      build: ./frontend
      ports:
        - "3000:3000"
      environment:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
      depends_on:
        - upload
      volumes:
        - ./frontend:/app
        - /app/node_modules